### ISSUE TITLE
Arab-Israeli War mislabeled, Optional Cards Missing

### ISSUE THREAD

**Issue by JustAnotherNerd** [kingcoyote/twilight#16]
Arab-Israeli War is marked as a Neutral Card, even though it's supposed to be a USSR event.

Also, Special Relationship, NORAD, and the Cambridge Five are missing from the list.

**Comment by kingcoyote** [comment]
Fixed in a17c2a5.

Optional cards were disabled by default on new games, but they are now enabled. I've also fixed Arab-Israeli War to properly be labeled as a USSR event.
